export default [
    {
      id: "1",
      name: "Moustiquaire",
      room: "entrée",
      tags: ["camping"],
      taken: false,
    },
    {
      id: "2",
      name: "Sifflet",
      room: "entrée",
      tags: ["camping"],
      taken: false,
    },
    {
      id: "3",
      name: "Gourde",
      room: "salon",
      tags: ["1 semaine+", "1-2 jours", "1 jour", "camping"],
      taken: false,
    },
    {
      id: "4",
      name: "Maillot",
      room: "chambre",
      tags: ["été"],
      taken: false,
    },
    {
      id: "5",
      name: "Parfum",
      room: "salle-de-bain",
      tags: ["1 semaine+", "1-2 jours"],
      taken: false,
    },
    {
      id: "6",
      name: "CNI",
      room: "entrée",
      tags: ["1 semaine+", "1-2 jours", "1 jour"],
      taken: false,
    },
    {
      id: "7",
      name: "Doudoune",
      room: "entrée",
      tags: ["hiver"],
      taken: false,
    },
    {
      id: "8",
      name: "Brosse à dent",
      room: "salle-de-bain",
      tags: ["1 semaine+", "1-2 jours", "camping"],
      taken: false,
    },
    {
      id: "9",
      name: "Appareil photo et chargeur",
      room: "chambre",
      tags: ["1 semaine+", "1-2 jours", "été", "hiver", "camping"],
      taken: false,
    },
    {
      id: "10",
      name: "Crème solaire",
      room: "chambre",
      tags: ["été"],
      taken: false,
    },
    {
      id: "11",
      name: "Jeux de société",
      room: "salon",
      tags: ["1 semaine+", "1-2 jours"],
      taken: false,
    },
  ];